### ISSUE TITLE
Edit ideological map to account for the dimweight

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#1]
Fix cutting lines and form ellipse of feasible coordinates

**Comment by lukesonnet** [comment]
@JeffreyBLewis should look at why the midpoint is outside of the ellipse on some votes (such as http://128.97.229.160/rollcall/H1131199).

We are going to probably scrap the yea-nay line and only draw the cutline for votes that have some positive PRE above a low threshold. This should make sure that we only draw cutlines for votes where they are both informative and helpful with respect to predicting votes. @adamboche and I can work on this after the schema change #22.
