### ISSUE TITLE
states115.json missing

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#100]
We have districts115.json but not states115.json. The code is smart enough to fall back to states114.json but it affects speed a little.

I assume the solution is just `cp states114.json states115.json` but I didn't want to presume there were no state boundary changes since last time.

**Comment by JeffreyBLewis** [comment]
Copied json114.json to json115.json. Done.

**Comment by JeffreyBLewis** [comment]
Done.
