### ISSUE TITLE
API Throttle / Quota

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#103]
I have implemented the API throttle / quota system and the search logging system.

This is a rough series of steps:
1. We calculate a hash of the user's identity in a secure way (see Wiki page on this subject for more technical details). This identifies the user for our search logs and quota tracking, since we don't have any API keys.
2. When a user hits an API, before doing anything we check their quota status
3. If they are over quota (or blacklisted by IP), we don't perform the operation
4. If not, we perform the operation, and add to their quota usage, and log the search
5. At some point, a scheduled process runs to reset quota usage

We log the search to a database with the following information: user hash; time of search; number of results (-1 for error); search query; extra search query metadata. We log the best available option of either the exact query dict sent to mongo OR the text provided by the user, depending on the stage in which the query fails or succeeds. This is in the collection `search_log`, while quota usage is in the collection `api_quota`. Neither needs to be part of the deployment process at all because basically logs and api quotas can be dropped no problem. The blacklist, whitelist, and settings are in the `model/auth.json` file, which is not stored on Github to protect our API keys for external APIs.

Currently only vote searches cost quota, every search successful or failed costs 1 quota point, unless the query takes a lot of processing power (seconds of execution) then it takes up to 10. You get 1000 per hour. We can update the quota limit, whitelist, and blacklist functions without restarting the server or doing anything. Blacklists and whitelists can be IPs, class Cs, or class Bs.

Member searches are honestly pretty fast, so I won't add quota to them. I will add quota to the District lookups because they're a bit more intense.

Luke, currently if someone is over-quota they're going to get a standard fail so existing error handling would be ok--if we get time in the future I will add an additional flag so you can directly notice that the user is over quota and actually prevent them from spamming us with queries. In addition, please set a specific user agent in Rvoteview if you can, since the user agent is part of the identity hash.

Going to leave this open as we continue development.

**Comment by aaronrudkin** [comment]
I implemented the quota on district lookups. 1 for the geocode, 2 for the address to district translation.

**Comment by lukesonnet** [comment]
I'm getting errors that authFile doesn't exist when calling searchVotes when trying to generate data. Are you still working on this or can I take over and debug some stuff?

**Comment by lukesonnet** [comment]
I see the problem. Can you ensure that the authFile dictionary is defined well enough in the last 'except' block at the top of the page? When I load the model python files for my usage in genData it doesn't load these json files.

**Comment by aaronrudkin** [comment]
I can do this for now, but this hack of "well, the relative path might be screwed up, so we waterfall a bunch of defaults and backups and backup backups" is not what we should be doing in general. Is there a general purpose solution for telling included python packages to set the path within the package?

**Comment by lukesonnet** [comment]
I remember having no luck with this before. I'll try again, has to be a better solution, so please don't add this to logQuota.py yet.

**Comment by lukesonnet** [comment]
Fixed.
