### ISSUE TITLE
Trying to Download 115th congress .ORD file give 404 error

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#107]
Just attempted to download 115th Congress ORD file.  I get a 404 error.

**Comment by aaronrudkin** [comment]
Can confirm that we have no ORD files for the 115th (house, senate, or both)

**Comment by adamboche** [comment]
We'll fix this.

**Comment by lukesonnet** [comment]
Data exists now, but this will have to be re-run once the data are fixed by Adam.
