### ISSUE TITLE
Code that depends on manual updating each congress

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#11]
A portion of our code requires updates each congress to ensure things do not break. We should inventory this code, look at impacts to the site if we fail to update each congress (i.e. will it break features or just display poorly), decide if can we automate the transition or is it necessarily manual, note which files are affected, etc. I don't think we'll forget to do the 2017 transition to the 115th, but by the time the next one rolls around, we might be less involved.

- Vote maps rely on the existence of a json file for each congress. If a map is not found for a given congress, the map will not display but the vote page will otherwise work. Jeff can speak to if it is possible to automate this further. We could also make a cron job to automatically copy this session's maps to the next session--I don't know what kind of errors this could lead to if we did. Maybe do this pre-emptively until 2020? We could also write error handling code to fall back on the most recent good map in the event that no maps exist. **Edit:** The vote map will now try to load a map from one congress ago if the current congress' map is missing.
- The maps used for the party control map rely on state boundaries that have "expiry date". Jeff has set the expiry dates to 2020. If the states expire, then in 2021 our map will just be blank. This requires updating the **/static/json/states_all.json** file. Does it make sense to maybe set them to 2050 (i.e. push the problem until we are dead or retired)? Do we expect any states to secede and/or split in two? Admission of new states isn't a problem--first, because we're not likely to passively forget when this happens. Second, because the error would only be the new state not appearing, nothing would happen to the map as a whole. I would recommend pushing the date at least a little bit past 2020.
- A variety of graphs rely on a hardcoded maximum congress number for setting x-axes. If we do not change this, data from current congresses will not show up on those pages. I think it probably makes sense to hardcode the maximum congress number in exactly one place, have all of the graphs read the maximum from that one place, and then if we're confident change that one place from hardcoded to dynamic depending on the calendar or we could create a cron job to dynamically pull the maximum congress number from the vote databases. Thoughts?

I have no idea if this is exhaustive. We should grep all code looking for 113, 114, or 115 (to account for off-by-one), as well as 2014, 2015, 2016, 2017, 2020, 2025, 2030. Most of this is my code but I'd appreciate it if someone else could hop in to help work through this.

**Comment by aaronrudkin** [comment]
**app.py** contains hardcoded 114s in two spots: the default congress to load for congress pages and the default map to show for party control maps. I think probably both of these can be replaced with a single hardcoded configuration variable or default to -1 and have the function look up the current db max congress if the argument is -1.

**Comment by lukesonnet** [comment]
> We could also write error handling code to fall back on the most recent good map in the event that no maps exist.

This seems to be the most sensible solution. In addition to this there should be a total to-do list of the manual things that need to be checked (like new district boundaries) and what intervals they need to be done at (every congress, every 10 years, etc...)

> we could create a cron job to dynamically pull the maximum congress number from the vote databases.

I think having a hardcoded congress number somewhere would work using this method. That's what my first thought was before reading your suggestion so I think we should run with this.

**Comment by aaronrudkin** [comment]
**views/parties.tpl**, **views/congress.tpl**, **views/partiesGlance.tpl** all have hardcoded 114s. These all run python code so they can easily pull from a hardcoded config file. I have some examples of reading json config files in the model folder (for example our auth info for the email api).

**Comment by lukesonnet** [comment]
The other option is just to let the max congress live in the meta collection and just call it from there (or indeed just get the max each time). Not sure this is practical for the website stuff but it would be fine for the /usr/scripts/ code (I know I have some hardcoded 114s in /usr/scripts/ and I don't know if any of Adam's code does but we already are connecting to the mongo so adding a call to get the current congress would be pretty cheap).

**Comment by aaronrudkin** [comment]
**/static/js/partyGlance.js**, **/static/js/party.js** both have hardcoded 114s.
**/static/js/explore.js** and **/static/js/party.js** have hardcoded 2016 values.

I think this is an exhaustive listing of hardcoded congress/year numbers in the website side (we should open an issue in the metadata repository to discuss the same issue on that side).

**Comment by adamboche** [comment]
Perhaps we can limit error if we reduce duplication of data, lest we forget
to update it some time.

max (db.voteview_rollcalls.distinct ('congress'))

should be pretty foolproof hopefully.

**Comment by aaronrudkin** [comment]
I created a file called **/static/config.json** which currently just contains one configuration entry: maxCongress, set to 114. I am updating all of the code that refers to 114 to instead read the number from this file. 

Then, someone who isn't me (Luke, if you have room on your plate?) can write a cron job using Adam's suggestion to check if the maxCongress from the db doesn't match the maxCongress from the json file. If they don't match, update the file. Set the cron job to run weekly.

**Comment by lukesonnet** [comment]
I'll do it right now. One problem with these cron jobs is that we will want to make sure they are portable/easily knowable. Is there a master crontab?

**Comment by lukesonnet** [comment]
I'll just use root for now I'm assuming.

**Comment by aaronrudkin** [comment]
If you mean where is the file, then I believe **/var/spool/cron/crontabs** (root only) contains what you want. If not through crontab, then manual cron jobs are in the **/etc/cron.daily**, **/etc/cron.weekly**, etc folders as appropriate. If you mean what user, then root should run all system tasks I think.

**Comment by aaronrudkin** [comment]
**/static/js/congress.js** has a static set of points where the VP/President of the Senate switches. This is used to make sure the Vice President is counted in the Senate Party Composition. Since we don't store Vice Presidential data for rollcall purposes, it doesn't make sense to read it from the database. We also can't read the President's party from the database because there are pretty wide swaths of history where the Vice Presidency is vacant. So this basically needs to be manual.

Say for the sake of argument that partisan control of the Presidency switches next year (. . .); if this code does not get updated, then it will still count the Vice President as a Democrat.

When we close this job, we should create a Wiki page for "periodic manual tasks".

**Comment by lukesonnet** [comment]
**/usr/scripts/metadata/updateConfig.py** is run every week and checks for the maxCongress, editing if necessary. That file should just be built out as we add to the config.json file.

**Comment by lukesonnet** [comment]
**/views/person,tpl** has a 2016 on line 54 that will need to change as the current congress changes. I'm not 100 percent sure of the syntax or the data so perhaps you could grab that little change @aaronrudkin, and then close this issue if you feel comfortable. I did a pretty comprehensive grep on the whole repository for 201[4567] and for 11[345] and that was the only pertinent hit that I found.

**Comment by aaronrudkin** [comment]
Whoopsie, missed that one. The Bottle syntax allows you to write straight python if you preface a line with %. I just changed 2016 to datetime.datetime.now().year and did an import datetime at the top of the person template.
