### ISSUE TITLE
Hacking the member tables on the explore pages to look nicer when few members are selected

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#110]
I did some hack that forced there to be only one column when there were fewer members selected on a rollcall page. This required making some ad hoc choices about how to set the number of columns given the number of people selected, but I think it looks a lot better.

I'm going to try to do the same for the explore pages.

**Comment by lukesonnet** [comment]
Happier with where this is now, but ideally it would rely on the size of the user's browser to do this more efficiently.

**Comment by aaronrudkin** [comment]
Yeah, uh,

**Comment by aaronrudkin** [comment]
Found the source of the issue and fixed it. When you modified the column thing, you used validSet.length to check for the number of valid members selected. That was smart, except that validSet.length being exactly 0 means there's no filter and you should show all of them. The show/hide code was respecting that but the column code didn't. Quick fix.
