### ISSUE TITLE
Multiple probability labels appearing sometimes

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#111]
I moved the mouse around the right edge of the ellipse and the label got dissociated from the mouse so additional labels appeared to track the mouse. I'm not exactly sure what the necessary condition is. Screenshot below.

http://128.97.229.160/rollcall/RH1150030

![image](https://cloud.githubusercontent.com/assets/19828875/21866381/d4a8ff00-d7fe-11e6-8537-71095693c6a9.png)

**Comment by aaronrudkin** [comment]
I can replicate this and will fix it.

**Comment by aaronrudkin** [comment]
This is fixed.

**Comment by aaronrudkin** [comment]
Okay, I also figured out what it was -- duplicated tooltip spawning code in the heat map and the decorate.
