### ISSUE TITLE
Search query performance currently lousy

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#114]
Not sure what happened and maybe we need more hardware, but simple text searches (including suggested searches) are currently insanely slow (>15  to 30 seconds).

**Comment by JeffreyBLewis** [comment]
Joe Luk just upped the memory on voteviewdev to 8G, not obvious improvement, but maybe we need to change some mongo settings, @adamboche?

**Comment by aaronrudkin** [comment]
Adam switched our text index over to a wildcard index a few days ago -- I think it would be valuable to try with and without that. I also think it would be valuable to ensure we run the vacuum command after any major DB change and look into any other optimization things we should be running.

**Comment by adamboche** [comment]
I'm getting 2-second searches or so. Which queries are 15+ seconds?

**Comment by JeffreyBLewis** [comment]
Foreign policy

For one or 

Taxes 


Jeff

**Comment by adamboche** [comment]
If I search *university of california* in the search box, it loads
apparently forever, but:

- almost immediately it says 104,715 votes found.
- the following query in the mongo shell completes in 0.4 seconds with
10,147 results

db.voteview_rollcalls.find(
{$text: {$search: "university of california"}},
{score: { $meta: "textScore" } }
).sort({score: {$meta: 'textScore'}}
).explain('executionStats')


Quoting the searches gives divergent results as well. Could someone who
knows the web api take a look at what's going on?

**Comment by adamboche** [comment]
I built a custom-weighted text index instead, but I'm experiencing similar behavior. Fast in the db, nonterminating on the site. 

db.voteview_rollcalls.find({$text: {$search: "\"election of the speaker\""}}, {votes:0, score: {$meta: 'textScore'}}).pretty().sort( { score: { $meta: "textScore" } } ).limit(20)

**Comment by adamboche** [comment]
I believe we are running out of RAM when we try to return results. If we add `.limit(20)` for the first page of results and `.skip(20).limit(20)` for the subsequent page it seems to work in the shell for queries that otherwise hit memory limits. This seems to work for textScore-sorted queries as well.

**Comment by lukesonnet** [comment]
These problems all seem to be due to an error in searchMembers that was trying to sort tons of members and we were running out of RAM. I limited it to 20 members after the sort and the problem seems to be solved.

**Comment by lukesonnet** [comment]
Please comment here if it is not.

**Comment by adamboche** [comment]
Looks good to me:

```
db.voteview_rollcalls.find({$text: {$search: "\"university of california\""}}, { score: {$meta: 'textScore'}}).pretty().sort( { score: { $meta: "textScore" } } ).limit(1)
```

Congratulating the women’s water polo team of the University of California, Los Angeles, for winning the 2007 NCAA Division I Women’s Water Polo National Championship, and congratulating UCLA on its 100th NCAA sports national title, making it the most accomplished athletic program in NCAA history
