### ISSUE TITLE
Vote map runs over legend in medium-size window

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#118]
![image](https://cloud.githubusercontent.com/assets/19828875/21947105/4fed59f0-d998-11e6-9942-9cb4cffce8f4.png)

Probably they should shrink or get stacked vertically to avoid this.

**Comment by aaronrudkin** [comment]
This shouldn't happen for now (the vote list gets pushed below the NOMINATE oval). I do want to do better than this, but I think it makes more sense to address as a comprehensive task to make the site mobile-ready than on its own. Given that the immediate bug is fixed, I will close.
