### ISSUE TITLE
Bottom-edge shapes clipped

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#121]
Legislators appearing on the bottom of the ellipse are clipped. 

http://128.97.229.160/rollcall/RH0820180
![image](https://cloud.githubusercontent.com/assets/19828875/21948157/2375c334-d99e-11e6-880b-fad70de7033b.png)

**Comment by JeffreyBLewis** [comment]
Yep.   Not sure why it clips the ones on the bottom, but not on the top.  I try to figure it out.
And apparently we have a bit of cutline problem, see
http://128.97.229.160/rollcall/RS1020525

**Comment by JeffreyBLewis** [comment]
Add to .clipPadding(4) to the construction of the DC scatterplot in voteChart.js.  Seems to have fixed the problem.   Misplaced cutline appears to have been a cached JS  problem.

**Comment by adamboche** [comment]
Same thing's happening on the right here:
http://128.97.229.160/congress/senate

**Comment by JeffreyBLewis** [comment]
Fixed.  Good catch.  Same problem as the other, but in another place in the code.
