### ISSUE TITLE
Vote descriptions strip final period?

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#126]
Some of the descriptions are full sentences and it looks off to me when the sentence doesn't end with a period. e.g. RH110195 has a period in the db but it doesnt appear on the site.

**Comment by aaronrudkin** [comment]
Sorry, what's the ID of this vote? You put RH110195 -- at least one digit is missing from the rollcall.

**Comment by adamboche** [comment]
Oh sorry, it looks like there's a field that has the description without the period in the db.  No problems then.
