### ISSUE TITLE
Sort by prob of votes doesn't handle abstentions correctly

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#130]
Right now when the votes on the member pages are sorted vote by probability, the Pr(yea) imputed for abstentions is used.  This isn't good.  We should penalize the abstentions so that they appear at the end of the list.

**Comment by lukesonnet** [comment]
Sorry, I believe we have them in an entirely separate list? Checking now it
appears we do. Did you see a vote where this occurred?

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by JeffreyBLewis** [comment]
Try http://128.97.229.160/person/14105 and sort the first page by vote prob.

**Comment by lukesonnet** [comment]
Oh sorry, member pages.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by aaronrudkin** [comment]
This should work.
