### ISSUE TITLE
What happened to the listing of the minor parties on the party page

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#131]
They used to be there and now they are gone.

**Comment by aaronrudkin** [comment]
Our ingestion workflow modifies the Opposition Party (which is the name of two unrelated parties, one in the 34th and one in the 36th) -- something in this broke, which cause the congresses active field for the Opposition party to be wrong, which broke display of all parties after the Opposition Party.

Temporary mitigation: saner error handling for the congresses active field. DONE.

Long-term fix: re-run the party stuff to fix the underlying data issue.

**Comment by aaronrudkin** [comment]
This is fully fixed.
