### ISSUE TITLE
No key votes for the 114th Congress revealed in search

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#132]
Do we have key votes for the 114th?  Do we have process to keep pulling those in?

**Comment by adamboche** [comment]
I added the 114th key votes from 2015, but it looks like CQ Press has not posted any 2016 ones yet. It seems likely from this that they put them up a year at a time. Doing this check is a little slow at the moment, so I'll leave this commented out for now and recheck later if they've added anything.
