### ISSUE TITLE
Log likelihoods in download csv files have the wrong sign

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#134]
Log likes in files such as 

http://128.97.229.160/static/data/csv/member/member_both_115.csv

are wrong.  Probably because we use an minimizer to solve the max likelihood.  Throwing a "-" in front of the reported numbers should do the job.   Should also probably add Geometric Mean Probability (GMP) which is exp(LL/(yeas + nays)).

**Comment by lukesonnet** [comment]
Issue #136 is now this issue.
