### ISSUE TITLE
Add proposer/sponsor/etc. to vote page, highlight them on ellipse

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#151]
Per Howard's recommendations, we should automagically match proposer/sponsor data from a rollcall to voter data in a rollcall and then display them in both the text and in the ellipse, highlighted.

**Comment by adamboche** [comment]
I will work on this

**Comment by adamboche** [comment]
@aaronrudkin I can set sponsor to the icpsr or id (etc) of the member. What field would make it easiest for you?

**Comment by adamboche** [comment]
I put in the sponsor's icpsr, currently running 1-105. Easy to change it to `id` if that's preferable. Still to do: 106+

**Comment by adamboche** [comment]
I think `id` is preferable so I changed it. `{sponsor: 'MH0120123'}`

**Comment by aaronrudkin** [comment]
ICPSR would be preferable since I think the vote data has ICPSR. I can write the mapping for free anyway when I do the join in downloadVotes so it's no problem if this is more convenient for you in any other case.

**Comment by aaronrudkin** [comment]
Sponsors are now noted on vote pages if present. Will do the highlights in a second.
