### ISSUE TITLE
Download votes icon is wrong image?

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#154]
I think we want 
![image](https://cloud.githubusercontent.com/assets/19828875/22361081/2ac5961a-e40b-11e6-8474-4f74ed29d40c.png) like we have for the cutting line download rather than 
![image](https://cloud.githubusercontent.com/assets/19828875/22361088/400e4abc-e40b-11e6-97f8-d9cc66d58673.png) which makes me think 'new document'

**Comment by lukesonnet** [comment]
Seems Aaron changed this, and I changed this for the stash as well.
