### ISSUE TITLE
Bug with member predicted probabilities for abstaining members likely to vote nay?

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#160]
https://voteview.polisci.ucla.edu/rollcall/RH1150063
- All voting Democrats voted Yea
- All voting Republicans voted Nay
- Near vertical cutline
- No weirdness with the likelihood function: the entire Democratic space is >=97% Yea, the entire Republican space is <1% Nay.
- A handful of each, Democrats and Republicans, abstained

Select just Republicans Not Voting -- observe in the ellipse that they all should very clearly be predicted to vote nay. Now mouse over their vote list.

Checked and verified the issue is in the data, not my display code:
`{ "text" : "Price, Tom (GA)", "cast_code" : 9, "prob" : 100 }`

Not sure how many other cases like this there are.

[Note: Adam is currently in the middle of a DB explosion so you might not be able to test on VVD right now]

**Comment by lukesonnet** [comment]
It's not just abstainers. The whole thing is messed up. On that vote just sort by vote probability. The lowest prob vote = yea is 97.

On it.

**Comment by lukesonnet** [comment]
"It's a feature"

**Comment by aaronrudkin** [comment]
Updated the member vote page label, the rollcall page column header, and the rollcall page tooltip to reflect this.
