### ISSUE TITLE
Chamber page Senate 115 ellipse missing

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#193]
It's present for the House and other congresses, just missing Senate 115. 

![image](https://cloud.githubusercontent.com/assets/19828875/22967267/ac3755a8-f31a-11e6-91c8-4aaec215d0e3.png)

http://128.97.229.160/congress/senate?congress=115

**Comment by aaronrudkin** [comment]
This fixed itself -- the root cause was Luther Strange getting appointed and his data being malformed and causing it to not display. @adamboche We should follow up by testing injecting purposefully broken data and ensuring it does not fail when it gets some.
