### ISSUE TITLE
Both Donnelly and Manchin are "the most conservative democrat in the 115th Senate"

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#195]
Mouse over the histogram

https://voteview.polisci.ucla.edu/person/20717/joe-donnelly
https://voteview.polisci.ucla.edu/person/40915/joe-manchin-iii

**Comment by aaronrudkin** [comment]
This ended up being a really stupid rounding error involving people who are in the <=0.005 percentile or >=0.995 percentile ideologically.
