### ISSUE TITLE
Vacant land

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#198]
From Howard:

> In the 2nd House, there is a district GA-01 and a district GA-1.  I believe that the GA-1 is simply vacant land that is part of no congressional district. I would label it more like GA-A and make the text. "This area was not part of any congressional district" to distinguish from vacant seats.  My experience with the older Voteview is that these "holes" recur on the frontier well into the nineteenth century.

**Comment by aaronrudkin** [comment]
Oddly, I can't seem to get any results in Georgia before the 15th Congress. It primarily had an at large district before then, but it did have a fixed district in the 1st and 2nd. But Howard's command suggests to me that we do have the data. Can someone give me a fixed address to check to replicate this?

**Comment by JeffreyBLewis** [comment]
That GA-1 is I believe a "-1"!  I think that were at this time some indian lands that were not considered (at least by by Martis) to be part of any CD.  I think GA also had some oddly named districts (like "Militia District One").  I will take a look to see what going on.   We might want @aaronrudkin to put in some logic for "-1" districts ("Indian land" or some such).   I will take a look at how often this happens.

**Comment by JeffreyBLewis** [comment]
I did some digging:  It turns that there are -1 areas in a number of states.  Here is a complete list:
AL-1    18
AL-1    19
AL-1    20
AL-1    21
AL-1    22
GA-1     1
GA-1     2
GA-1     3
GA-1     4
GA-1     5
GA-1     6
GA-1     7
GA-1     8
GA-1     9
GA-1    10
GA-1    11
GA-1    12
GA-1    13
GA-1    14
GA-1    15
GA-1    16
GA-1    17
GA-1    18
GA-1    19
GA-1    20
GA-1    21
GA-1    22
IN-1    17
IN-1    18
IN-1    19
IN-1    20
IN-1    21
IN-1    22
NC-1     1
OH-1     7
SC-1    13
SC-1    14
TN-1     8
TN-1     9
TN-1    10
TN-1    11
TN-1    12
TN-1    13
TN-1    14
TN-1    15
TN-1    16
TN-1    17
TX-1    28
TX-1    29
TX-1    30
TX-1    31
I will double check that this is all indian land and then we decide what to display on rollover.

**Comment by JeffreyBLewis** [comment]
The doc files for the CD data collection, I looks like the -1 code means "unincorporated area."  I will try to confirm exact wording in Martis and also see if there is some extra detail available.  But for now, we can probably go with "Unincorporated land" on roll over.

**Comment by aaronrudkin** [comment]
This is implemented in `/static/js/voteCharts.js`. The code for detecting unincorporated land is in `function checkUnincorporated()`, and the label is on line 438 if anyone wants to tweak either.
