### ISSUE TITLE
Ellipse is black

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#218]
Nominate is 0 on this vote, because it has one dissenter and a few abstainers.
http://128.97.229.160/rollcall/RH1150256

![image](https://cloud.githubusercontent.com/assets/19828875/25759101/f56b5342-3185-11e7-89cf-1c430cab6669.png)

**Comment by JeffreyBLewis** [comment]
Fixed.  Looks like we renamed the vote totals keys in the data object from yea and nay to yea_count and no_count.   I made the changes and committed.  I checked some other lopsided votes and everything seems to be in order.
