### ISSUE TITLE
DB Schema migration

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#22]
This is an open issue to track our db schema change.

**voteview_rollcalls**
- [x] synthID to _date_chamber_rollnumber_
- [x] result to _vote_counts_
- [x] votes: {id, v, p} to _votes: {icpsr, cast_code, prob}_
- [x] Add prob to votes @lukesonnet 
- [x] resultparty to _party_vote_counts_ -- and keys change from party labels to party numbers
- [x] code to _codes_
- [x] nay to _nay_count_
- [x] yea to _yea_count_
- [x] pre and classified fields missing from nominate @lukesonnet
- [x] keyvote to _key_flags_
- [x] support to _percent_support_
- [x] shortdescription to _short_description_
- [x] New description waterfall: vote_desc, vote_document_text, description, short_description, vote_question, question
- [ ] Fix indices @adamboche 

**voteview_members**
- [x] stateAbbr to _state_abbrev_
- [x] bioName to _bioname_ (lowercase)
- [x] party to _party_code_
- [x] districtCode to _district_code_
- [x] bio to _biography_
- [x] stateName, cqLabel, startdate, lastmeans, occupancy, state, partyName, geo, enddate, dimweight, stateCode ALL REMOVED -- verify OK
- [x] Add born and died @adamboche 
- [x] Crosswalk social fields @aaronrudkin
- [x] wikiStatus to _wiki_status_
- [x] Nominate: oneDimNominate to _dim1_; geoMeanProbability to _geo_mean_probability_; numberOfVotes to _number_of_votes_; twoDimNominate to _dim2_; logLikelihood to _log_likelihood_; numberOfErrors to _number_of_errors_.

**Reimport voteview_parties**

**Web code check**
- [x] Search votes rewired
- [x] Download votes rewired
- [x] Vote view page rewired
- [x] Member bio page rewired
- [x] Congress page rewired
- [x] Parties pages rewired
- [x] All code pointing to test_voteview
- [x] Drop voteview db and renamed test_voteview to voteview
- [x] All code pointing to voteview
- [ ] Deployed to production server

**Comment by lukesonnet** [comment]
Search votes is rewired, although it now is showing votes for rollcalls that don't have nominate fields, which used to be hidden. Default should be hide these from the search page because we should at least have conditionally estimated nominates within a few hours of any new votes being added to the db.

The vote pages work (if the nominate data exists). However, the links to member pages are broken.

Please note that I wrote a generic function to waterfall in **views/search_list.tpl** called waterfall. That might need to go somewhere else if we want to use it for the vote page as well.

**Comment by aaronrudkin** [comment]
Okay, I'm updating the original post here with the field names we need to fix.

**Comment by lukesonnet** [comment]
This issue should also not be closed until all of the user-facing documentation is updated.

**Comment by aaronrudkin** [comment]
I believe we have two outstanding index issues here:
1) The fulltext index was set up for just description. I corrected this, but the build script should probably be updated to reflect the actual intent.
2) The sparse index for key_flags is not set up at all.

Other than that the schema move was a success.

**Comment by aaronrudkin** [comment]
The sparse index thing is still weird--I don't think it can be done in pymongo, so we overrode it with a javascript file that mongo runs directly in build_edits.sh. 

@adamboche Where are the main indexes being built now? Probably somewhere in ingestion? We should ensure we all know where so as we update our fulltext indexing strategy it's all set up properly.

**Comment by aaronrudkin** [comment]
Post-launch, we need to deal with the fulltext thing.

**Comment by adamboche** [comment]
I think I know how to do the fulltext thing. Will report back.

**Comment by adamboche** [comment]
I've set up a wildcard text index in rollcalls and members, so all string
fields should be indexed automatically as they are added.

**Comment by aaronrudkin** [comment]
Isn't this going to index a massive amount of garbage?
