### ISSUE TITLE
Distorted member photos

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#29]
The thumbnail photos in the list are sometimes distorted even if they're correct on the actual member page.

In the 104th senate, for instance:

![image](https://cloud.githubusercontent.com/assets/19828875/18559598/dce91ba2-7b2c-11e6-9de1-24765b4f4023.png)

![image](https://cloud.githubusercontent.com/assets/19828875/18559606/e6950be8-7b2c-11e6-92c0-e9a1a4284352.png)

**Comment by aaronrudkin** [comment]
Ah, yeah, this probably will probably impact any portrait member photo. Probably easier to crop the photos than fix the display.

**Comment by aaronrudkin** [comment]
Okay, I whipped up a shell script to quarantine the landscape photos. We lose 302 photos to this but I am confident the remaining photos should display fairly well. I am going to experiment with automatic smart cropping on the landscape and see how badly that mangles things.

**Comment by aaronrudkin** [comment]
I did a shell script to center-crop to 4:5 aspect ratio all of our landscape images. The effect generally looks good. I have deployed the cropped files to fix it.

There were 19 files that did not crop well.

Can someone who is not me download this zip file, manually crop the images inside to a 4:5 aspect ratio (100 width for every 125 height) as appropriate and then reupload them to vvd's /static/img/bios/ folder (you can use sftp) and do a commit? Then close this issue

**Comment by JeffreyBLewis** [comment]
I cropped the 15 photos referenced above and uploaded and committed.  There is one remaining real problem which is that 009662.jpg does not appear to contain an image of a person at all!    Also, while not strictly speaking a problem, I think 015427.jpg is Joe Kennedy.  I am sure we could find a better image of him that the one that I just cropped.

**Comment by JeffreyBLewis** [comment]
I updated to a better picture of J. P. Kennedy.   009662 (Daniel Verplanck of NY) has as is picture a picture of his house.  It from wikipedia,  I did a little searching for a better image of him, without success.   I am going to call this closed and we can ad 009662 to the short list of folks for whom we do not have images.

**Comment by aaronrudkin** [comment]
Thanks Jeff! If you notice any other photos that seem bad, feel free to keep adding to the manual folder as necessary!

**Comment by adamboche** [comment]
Still present for some

**Comment by aaronrudkin** [comment]
I have a maintenance script in `/usr/scripts/voteview_metadata/updateDB/imageAspectRatio/` called `smartcrop-batch`. Our ideal aspect ratio is 5:4 (1.25). The script scans for anything about 1.35 (too long) or below 1.15 (too wide) and uses facial recognition to crop to 5:4 as best as it can. So the absolute most that a remaining image will be squished or stretched is 8%.

Feel free to alter the parameters here if you want the tolerance to be a little lower, but we cause quality degradation by re-encoding a JPG so unless you think the aspect ratio is real bad I wouldn't.
