### ISSUE TITLE
Photo of wrong person

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#303]
The page for Shea-Porter, Carol is displaying the photo of Porter, Jon.

https://voteview.com/person/20731/carol-shea-porter

**Comment by JeffreyBLewis** [comment]
I fixed this on production.  Not sure what the best way to get the new image into the repos.  Here is the img file.
![020731](https://user-images.githubusercontent.com/4761445/29181131-e2334616-7dae-11e7-8cbd-aa92317de6a2.jpg)

**Comment by JeffreyBLewis** [comment]
New file uploaded to repos.
