### ISSUE TITLE
Footer does not appear on bottom of pages that do not require scrolling

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#46]
The footer sticks to the bottom of pages that you have to scroll to, but does not stick to the bottom of pages that take up less room than the window on your browser. Compare the parties page to the data page, for example.

I tried to fix this in **base.tpl** some time this summer but I couldn't make it work.

**Comment by aaronrudkin** [comment]
The reason the footer triggers on scroll was to prevent a flash of the footer before the main content loads on pages that use ajax loading for the content--so I definitely think we shouldn't fix this by disabling the footer trigger.

But yes, I see that it does not correctly load on non-scrolling pages that _don't_ have an ajax load. Thanks for the report on this. I'll take a stab at it.

**Comment by aaronrudkin** [comment]
Explicitly include /static/js/footerFixed.js in pages that have no ajax / page scroll and this will be fixed.

**Comment by lukesonnet** [comment]
Doesn't force it to bottom on short pages, though?
