### ISSUE TITLE
Dots to members on vote page not working properly in narrower window

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#5]
http://voteview.polisci.ucla.edu/rollcall/H1141180

![image](https://cloud.githubusercontent.com/assets/19828875/17126790/30444b6e-52b5-11e6-890e-3156a8b443a1.png)

**Comment by lukesonnet** [comment]
There is quite a lot that fails on smaller windows, to be honest.

**Comment by aaronrudkin** [comment]
I haven't done anything with media for lower horizontal resolution stuff. This particular bug is fairly fixable (force column width to remain decent by simply lowering the number of columns).

**Comment by aaronrudkin** [comment]
I put something in the CSS to prevent this specific bug by forcing a minimum width. We should open another issue in a month or two to discuss mobile / low res issues more broadly.
