### ISSUE TITLE
Member page partially broken for members without nominate

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#52]
Members without nominate data do not load the ideology histogram, and much of the other javascript loading fails. The failure is silent though, so it's not immediately clear to me where the actual error is.

**Comment by aaronrudkin** [comment]
The issue here is that I correctly suppressed the ideology histogram, but the same code that fires that off also does things related to vote display and searching. I need to decouple this stuff.

**Comment by aaronrudkin** [comment]
This is fixed, I decoupled the vote search stuff from the nominate histogram stuff. Note: Many members who probably should have NOMINATE don't. @lukesonnet @adamboche can you guys ensure that NOMINATE scores are cross-filled for members that have them in some congresses and not others and then close this? Thanks. Just leave an emote to verify you've seen this.

**Comment by adamboche** [comment]
Yep we'll make sure this always happens.

**Comment by aaronrudkin** [comment]
OK I'll close then, thanks.
