### ISSUE TITLE
Suggestions being sent when facet search is chosen

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#53]
On the main page, open the advanced search. Wait for a suggestion to pop into the text box. If there is a suggestion in the box when you click a checkbox or enter a number into an input field it sends the suggestion as if it were the user query.

To nullify this we could:
- have no suggestions when the advanced pane is open
- clear the search bar when facet is clicked if nothing has been manually entered in to box
- turn off suggestions all together, or display them somewhere besides in the search bar itself
- don't allow the field to be submitted if the search bar has never been in focus

**Comment by aaronrudkin** [comment]
This doesn't quite happen to me. I opened the advanced search, waited for a suggestion to pop in, and clicked a checkbox, and the search behaved as expected. I think this is probably happening in certain cases, we just need a clean replication so I can debug it.

**Comment by lukesonnet** [comment]
I can't recreate this. I'll reopen it if I find it.

**Comment by lukesonnet** [comment]
I figured this out, when you close the developer console it fires some kind of focus event which selects the box. Then if you search or click one of the facet options it includes that selection.

This is a pretty minimal edge case that is easily fixed by users just by entering the query they want. Leaving it closed.
