### ISSUE TITLE
President member pages are quite broken

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#61]
The flag isn't working, a bunch of the grammar is weird, and the previously served lines link to other presidents.

Example: http://128.97.229.160/person/99902

**Comment by aaronrudkin** [comment]
But other than that, Mrs. Lincoln, how was the play?

**Comment by lukesonnet** [comment]
Actually, it says lincoln served until after he was shot http://128.97.229.160/person/99884

Fixing this now.

**Comment by lukesonnet** [comment]
If only they had some top rate actors like Mr. Booth.

**Comment by aaronrudkin** [comment]
@lukesonnet Your commit to fix people serving after death has an error; for people who have not died, Adam sets the died field to null (None in Python), and any numeric value is greater than that in a comparison. I fixed it in the member bio page, but just leaving this comment in case there's somewhere else that's using this data.
