### ISSUE TITLE
Labels on percentage support slider are misaligned

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#64]
Labels are not appropriately centered on the percentage support slider on the advanced search facet.

**Comment by lukesonnet** [comment]
It looks like there are some issues with slider labels when they are generated by other events (see: https://github.com/seiyria/bootstrap-slider/issues/467)

I tried to recreate it in Javascript on click and it works well (it actually places the % labels on the slider and it shows a range being selected), but it doesn't load properly, which is an issue raised on the bootstrap-slider repo.

**Comment by aaronrudkin** [comment]
Note that although I am marking this as closed, it is still possible to get a momentary flash of misaligned labels if you toggle the Support chevron and then immediately mouseover the tooltip before the relayout event fires. But this is good enough.
