### ISSUE TITLE
Description cascade

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#67]
A couple more fields are available: `vote_title`, `vote_question_text`, and `amendment_author`. They could go right before `description`, perhaps. This will help for recent congresses in House and Senate votes that may have them.

**Comment by lukesonnet** [comment]
Added these to the waterfall, still doesn't help link amendments to bills but is much better I think. Closing for now.

**Comment by aaronrudkin** [comment]
This didn't get added to the waterfall for the member vote list.

**Comment by lukesonnet** [comment]
That is what that last commit does.

**Comment by aaronrudkin** [comment]
I swear when I checked earlier it wasn't in the waterfall somewhere. Maybe I'm being stupid.

**Comment by lukesonnet** [comment]
Can we close this or am I missing something?
