### ISSUE TITLE
Scroller is overzealous when zoomed in

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#73]
Go to a roll call, e.g. http://128.97.229.160/rollcall/RH1141274. Zoom in on the northeast. The right-hand side of the map no longer highlights on mouseover districts, and clicking on that part of the map activates the vertical scroller.

**Comment by aaronrudkin** [comment]
I think this is connected to how I solved #57. I need to look more into the slider component I use to ensure I can get this right.

**Comment by aaronrudkin** [comment]
I think this is solved after the commit I just made, but the solution is a weird hack so I'm going to leave this open.
