### ISSUE TITLE
Ctrl-click to open vote page in new tab

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#74]
From the list of rollcalls, I want to be able to ctrl-click a vote and open a new tab of the vote page.

**Comment by aaronrudkin** [comment]
I fixed this, sort of. You can now do this from the body of votes.

You cannot do it from the header of votes--this is an HTML limitation. You can't have nested link commands, so to turn it on I'd have to turn off all the interactive elements in the header, including the toggle box for the vote export. See discussion here: http://stackoverflow.com/questions/9882916/are-you-allowed-to-nest-a-link-inside-of-a-link
