### ISSUE TITLE
Speed Issue: House district map files too large.

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#77]
If you look at the house district maps, they begin around 215kb in the first house, ramp up to 600kb-850kb from the 100th-112th... and then jump in size to 1.2MB for the 113th and 114th. There's a palpable load time difference between votes in the 112th and votes in the 113th.

(Note this is separate from #23 which is the states_all.json for the party control maps.)

Any way we could regenerate the 113th and 114th house maps with less detail or is there something intractable about the 2010 redistricting that's pushing up the level of detail required?

**Comment by JeffreyBLewis** [comment]
Smaller maps made and committed for 113th and 114th Congress.  Seem to work/look fine.
