### ISSUE TITLE
Given date ranges on parties page

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#79]
Right now we show the congress range for each party which is good, but it would probably all be good to give date ranges.  I would be cool to precompute the date of the first and last date on which a member of each party cast a vote.

**Comment by aaronrudkin** [comment]
I precalculated these date ranges for all members and all parties, so it's in the database. I did add the dates to the page, but they're ugly and I think we should think more about which information to display and how to lay it out.

**Comment by aaronrudkin** [comment]
We lack information to identify this quantity exactly--for instance, suppose I am a Farmer-Laborer, and then half-way through Congress X, I switch to being some other party (say, Democrat). Suppose further that it's a switch that a priori Keith identified as being not one that requires a new ICPSR. Then, for congress X I am either listed as a Democrat or Farmer-Labor, but not both. What this script does is identifies the first and last dates that a member-congress belonging to this party voted, and so it will be slightly off at the intra-congress level. We have no way of solving this presently.

Given that restriction, this is fixed on dev and can be closed.
