### ISSUE TITLE
Back button into my district page 

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#84]
On the my district page, click on a row, let the legislator page load, then press back. I return to the district page, but I get

> Error: The address you entered was from outside United States. (Malaysia)

**Comment by aaronrudkin** [comment]
Basically, when you press back, instead of using the geolocation data to do the search, it just searches the text "MY LOCATION" -- you get the Malaysia error because of "MY". Will fix shortly.

**Comment by aaronrudkin** [comment]
Fixed.
