### ISSUE TITLE
Clicking location text box to erase text

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#85]
On district page, clicking on MY LOCATION could erase MY LOCATION, allowing the user to type into an empty box, instead of having to erase MY LOCATION before typing. Small thing, but nice to have.

**Comment by aaronrudkin** [comment]
Yes, this is true--I will also be adding a little pin icon to re-load your location.

**Comment by aaronrudkin** [comment]
This is fixed as well as general improvements to location lookup. Also emailed Joe Luk at SSCNET to see if we can get a domain for the test server to improve our ability to test and iterate on this stuff.
