### ISSUE TITLE
Clarify which legislator was in unlabeled rows

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#86]
On the district page, there are unlabelled rows when people serve multiple terms. It'd be good to clarify whether it's the legislator above or below who was in office at that time. For example,

![image](https://cloud.githubusercontent.com/assets/19828875/19880971/010de33a-9fbf-11e6-8b77-c83ff785990f.png)

**Comment by aaronrudkin** [comment]
I gave up trying to make the sparse table look good for now, so I just restored the legislator name. Post-launch I will look at improving the visuals of the table.
