### ISSUE TITLE
Text search doesn't find enough items

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#89]
Searching _tariff_ on http://128.97.229.160/ gives 8 results, but there are 601 items with `description` containing _tariff_.

```
> db.voteview_rollcalls.find({description: /tariff/i }).count()
601

```

**Comment by lukesonnet** [comment]
When you do this search without quotes, even if you use _description:tariff_ it hits the full text index. So the problem here is probably that there is too much text in each vote that is in the index (or as a consequence the score threshold is simply too high).

Will investigate.

**Comment by lukesonnet** [comment]
The index only has _vote_desc_ in it...

**Comment by adamboche** [comment]
Whoops. Fixed.
