### ISSUE TITLE
Increase statefulness

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#91]
It would be nice if we could maintain information about the user state a bit more easily. What's occurring to me at the moment is:

- Informative, clean search URLs
- Functional Back and Forward browser commands from every page

This might be a good place to make note of other statefulness requests as well.

**Comment by aaronrudkin** [comment]
I think with every page having slugified links and HTML5 state saving for the search stuff, this is done. It won't be perfect (for example, the faceted advanced search in the search page, and pressing back onto a user page that had loaded dozens of pages of votes) but I think it's pretty operational. Let's open a new issue with any specific state problems and we'll go from there.

**Comment by adamboche** [comment]
@aaronrudkin That looks great!
