### ISSUE TITLE
Big list of things to check

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#92]
Stack Exchange has a list of ["What things should a programmer implementing the technical details of a web application consider before making the site public"](https://softwareengineering.stackexchange.com/questions/46716/what-technical-details-should-a-programmer-of-a-web-application-consider-before). This may be useful to double-check in case we missed something.

If this seems useful, we might want to create individual github issues for specific items on the list.

**Comment by aaronrudkin** [comment]
This kind of thing is definitely a good practice. I think there are two main things from this list that matter: 1) Mobile-friendliness, which we won't have at launch, and 2) Resource limits and throttling on the AI, which we should have at launch. 

We have no user-inputted data and no user-facing communication (comments sections, etc.), no user accounts or passwords, most of the optimization stuff is done with HTTP2, we don't use cookies for anything we don't absolutely need to and store minimal data in those cookies (just a session ID for carts). We're not SEOed for individual votes right now but we also can't be until we get canonical names for votes. 

I will make it a priority to try to implement the skeleton of an API throttle this weekend.
