### ISSUE TITLE
Abs/Abstain/Absent -> Not voting

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#93]
Anywhere that says Abs/Abstain/Absent should be changed to indicate _Not voting_.

**Comment by aaronrudkin** [comment]
Updated "Absent" to "Not Voting" in several places; but in places where we can only fit the short "Abs", what should we use? I do not think "N.V." is intuitive at all and I would figure "slightly incorrect but comprehensible" is better than "technically correct but incomprehensible", no?

**Comment by adamboche** [comment]
I think I'd be ok with _Abs_ for the abbreviated form, @JeffreyBLewis what do you think?

**Comment by JeffreyBLewis** [comment]
I agree that Abs does dual duty and is perfectly acceptable.

**Comment by aaronrudkin** [comment]
With my last commit, this is done, then.
