### ISSUE TITLE
New decorate code breaks display of NOMINATE plots that don't have rollcalls.

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#97]
The new decorate code breaks any place where we display a NOMINATE plot but do not have a rollcall (i.e. the master plots for a congress, for example)

http://128.97.229.160/congress/senate

The issue is the line at the beginning:
`        var vn = data.rollcalls[0].nominate;`

If there's no rollcalls in the data this errors. I think we sanity check appropriately later so this is just a recent change. I didn't want to fix it because I wasn't sure if you were still working on decorate.

**Comment by JeffreyBLewis** [comment]
Yes.  I think we are business on this.  I have turned the sanity checking back on and moved definition of vn back inside the block in which it is known to exist. 

http://128.97.229.160/congress/senate now renders as expected.

Best,

Jeff
