### ISSUE TITLE
Heat map events 

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#98]
Votes with nominate cutlines now display a heat map showing probability of a yea vote.  I have wired up a tooltip and an interactive legend in the prototype at http://leela.sscnet.ucla.edu/nomheat.   Probably most efficient to get a bit of @aaronrudkin 's attention to bring the legend and event handling into production.   Need to have some sort of event pass through to deal with the stack of SVG objects that comprise the display.   Also, need to integrate some CSS from the prototype and to properly place the legend DIV.

**Comment by lukesonnet** [comment]
We should also have a tooltip that checks if PRE exists and is less than 0.05, so it is hard to say this vote is ideological (in two dimensions) so there is no cutline/shading. It should also display what the PRE is.

**Comment by lukesonnet** [comment]
The heat map makes dragging around or even drawing a selection box next to unbearable now that my machine has been open for a while w/ other apps running. Is find on vote without cut line.

Compare: http://128.97.229.160/rollcall/RH1140043 with http://128.97.229.160/rollcall/RH1141267

**Comment by JeffreyBLewis** [comment]
I turned off all of the event listeners on the map and reduced the number of hex patches in the heat map a great deal.  @lukesonnet see if that helps.

**Comment by aaronrudkin** [comment]
We can dramatically reduce the number of hexes rendered on many votes if we choose not to render any hex that has a colour value sufficiently close to white (i.e. probability arbitrarily close to 0). On a standard screen, p<~0.04 is indistinguishable from matte white. 

Especially in party divided votes this would drop the number of hexes by half.

**Comment by aaronrudkin** [comment]
I implemented this. I notice a major performance increase on my Macbook. On the first vote on the front page, of 572 hexes, 202 of them have p<0.05. That's a substantial reduction in rendering burden. 

Jeff, this still requires us to precompute the nominate parameters for each hex; is there some logic we could use to break from the grid logic early?

**Comment by JeffreyBLewis** [comment]
I don't think it would be easy or worth it.  The probability is not sure to be monotone and is very cheap to calculate.  I doubt that drawing these hexes is really much of problem, but I do agree that there is little reason to calc  the boundaries of hexesthat don't require any shading.   We could increase that number by default shading the Y side of the this line maximally and then filling in the hexes that are appreciably less than fully saturated, but it is hard to imagine that this would create a ton of performance gain and filling that y part of the circle isn't totally trivial anyway.    There was a bunch of ugly that did that which we got rid of when went to the heatmap, much cleaner.   I have messed around with the density of hex the grid and haven't really noticed much change in load time, so you would have to convince me that there is something to be gained here.

**Comment by aaronrudkin** [comment]
It's not upfront render time that's the issue--on my MB (again, cell phone processor, so definitely not very fast) I got substantially better responsiveness on selections and tooltipping after I removed half the hexes.

Point taken on the non-monotonicity--so we definitely need to calculate the entire grid in advance.

**Comment by JeffreyBLewis** [comment]
Super weird that the selector cares about the # of hexes in a layer that is not associated with the selector, but dc/d3 works in mysterious ways.   Maybe we just call this one closed for now. If we notice a problem, we can get a little cuter with the hex drawing.
