### ISSUE TITLE
Double checking cutline angles

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#99]
Cut lines for first votes of the 115th seems like they might be tilted the wrong way.   I would be confirm that cutlines produced by conditional python-based estimation are generating the same slopes (roughly speaking) as when generated by legacy DWNOM and then double check all of the cutline math.  I will do the later if @lukesonnet can do the former.

**Comment by JeffreyBLewis** [comment]
The seemingly odd cutline in 

http://128.97.229.160/rollcall/RH1150001

is perhaps simply due to the one GOP defection from Ryan on the speaker vote.  The cutline line is as expected on second vote, see
 
http://128.97.229.160/rollcall/RH1150002

which is a fully party-line vote.  Still should probably confirm that all is correct one last time.

**Comment by aaronrudkin** [comment]
This is not the issue that you intended to bring up, but I wanted to leave a comment:

Intuitively, it is strange to me that the single defection produces enough leverage on the cutline to flip it like that, such that the speaker vote has an apparently negative slope and the subsequent vote apparently positive. 

I get that in any near-fully party line vote there are arbitrarily many equally valid cutlines near a vertical line that will work, but do we not have a mechanism to coerce stability such that we aren't swinging wildly around that central space depending on individual votes? I guess what I mean is that to a lay person the lines on those two votes look very different although substantively nothing is different.

I'm imagining a bootstrap approach to fitting the cutline, but even something like re-plotting the cutline with the few lowest probability votes dropped would induce stability, right?

**Comment by lukesonnet** [comment]
I'm not sure why we want to coerce this behavior. If we don't like it, then we don't like nominate.

**Comment by lukesonnet** [comment]
Well it only moved a tiny bit so that isn't it. I think this is just nominate being nominate.

**Comment by JeffreyBLewis** [comment]
Ok, great.  Thanks for checking.   As for the bigger question, it's not the case that the various cut lines are equally valid (at least under the model).   The max lik estimated line is the what it is and is (probably) unique.  It is true that that estimated cutting line for (near) party line votes is pretty noisy because of the (near) separation.   The heat maps are actually pretty useful in understanding what is going on there.

**Comment by aaronrudkin** [comment]
Yeah, I guess I was surprised that a single vote defection, something that should be an error, could have so much leverage on the likelihood function that it could swing the cutline angle 40 degrees or more. I'm less concerned with "fixing" it and more concerned with wondering how to best convey the information to novices who might think the votes are meaningfully different when in reality it's just NOMINATE being sensitive.

The heatmap does help (although being yellow the gradient is not as clear as it could be -- I will implement the mouseover as best as I can to try to help with that).

**Comment by lukesonnet** [comment]
Aaron, see Poole's optimal classification where the cutlines on divided votes would truly be undefined.

I've implemented a simple check for at minimum 25 non-abs votes for the conditional updates. Thought it would be complicated but counting votes in the nominate payload is sufficient.

Discussion about heat maps and nominate info is super important but belong elsewhere, bc I think this issue is closed.
